export interface ChannelMemoryStore {
  /**
   * Saves a new memory for a specific channel topic/angle.
   */
  saveMemory(params: {
    channelId: string;
    topic: string;
    angle?: string;
    contentId?: string;
    expiresAt?: Date;
  }): Promise<void>;

  /**
   * Searches for previous memories in a channel related to a topic.
   */
  searchMemory(channelId: string, topicQuery: string): Promise<Array<{
    id: string;
    topic: string;
    angle: string | null;
    contentId: string | null;
    coveredAt: Date;
    expiresAt: Date | null;
  }>>;
}

export interface WorldKnowledgeStore {
  /**
   * Upserts an entity and its facts. 
   * The embedding should be generated by an LLM provider and passed in.
   */
  upsertEntity(params: {
    entityType: string;
    entityName: string;
    facts: Record<string, any>;
    sources: any[];
    embedding?: number[];
    expiresAt?: Date;
  }): Promise<void>;

  /**
   * Searches for entities using vector similarity.
   */
  searchSimilar(embedding: number[], threshold: number, limit?: number): Promise<Array<{
    id: string;
    entityType: string;
    entityName: string;
    facts: Record<string, any>;
    sources: any[];
    similarity: number;
    lastVerifiedAt: Date;
  }>>;

  /**
   * Retrieves a specific entity by exact type and name.
   */
  getEntity(entityType: string, entityName: string): Promise<{
    id: string;
    facts: Record<string, any>;
    sources: any[];
    lastVerifiedAt: Date;
  } | null>;
}

export type SignalTier = 'short' | 'mid' | 'long';

export interface PerformanceIndexStore {
  /**
   * Records a new performance metric.
   */
  recordMetric(params: {
    channelId: string;
    platform: string;
    metricType: string;
    value: number;
    signalTier: SignalTier;
    contentId?: string;
  }): Promise<void>;

  /**
   * Retrieves aggregated metrics.
   */
  getMetrics(params: {
    channelId: string;
    platform: string;
    metricType: string;
    timeRangeStart: Date;
    timeRangeEnd?: Date;
  }): Promise<Array<{
    id: string;
    value: number;
    signalTier: SignalTier;
    contentId: string | null;
    recordedAt: Date;
  }>>;
}
